import { GET_MENU } from "../actions/menuActions";

const initialState = {
  loading: false,
  errorMessage: null,
  menu: [
    {
      id: 1,
      image: "salad",
      name: "Salads",
      description: "",
      isImage: 4,
      iCnt: 3,
      items: [
        {
          id: 1,
          name: "Green Salad",
          description: "Freshly cut vegetables",
          price: 10,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 7,
          count: 0,
        },
        {
          id: 2,
          name: "Brinjol & Cottage cheese salad",
          description: "Deep fried brinjol and cottage cheese",
          price: 15,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 6,
          count: 0,
        },
        {
          id: 3,
          name: "Chicken Tikka Salad",
          description: "",
          price: 15,
          nonVeg: "No",
          icon_id: '["1"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 5,
          count: 0,
        },
      ],
    },
    {
      id: 2,
      image: "soup",
      name: "Soups",
      description: "",
      isImage: 3,
      iCnt: 5,
      items: [
        {
          id: 4,
          name: "Dal soup",
          description: "Freshly boiled Indian lentils with mix vegetables",
          price: 12,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 11,
          count: 0,
        },
        {
          id: 5,
          name: "Tomato Soup",
          description: "Tomato soup",
          price: 12,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 4,
          count: 0,
        },
        {
          id: 6,
          name: "Mushroom Palak Soup",
          description: "Freshly cooked mushroom and spinach soup",
          price: 14,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 7,
          name: "Chicken Soup",
          description: "Chicken soup with Indian herbs",
          price: 14,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 4,
          count: 0,
        },
        {
          id: 8,
          name: "Mutton Soup",
          description: "Mutton soup with Indian herbs",
          price: 16,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
      ],
    },
    {
      id: 3,
      name: "Vegetarian Snacks",
      image: "veg_food",
      description: "",
      isImage: 3,
      iCnt: 9,
      items: [
        {
          id: 9,
          name: "Samosa (2 pcs.)",
          description:
            "Crispy puffs stuffed with spicy potatoes and green peas",
          price: 12,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 22,
          count: 0,
        },
        {
          id: 10,
          name: "Paneer Pakora (6 szt. / 6 pcs.)",
          description: "Indian cottage cheese battered and deep fried",
          price: 16,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 13,
          count: 0,
        },
        {
          id: 11,
          name: "Mix veg. Pakora (8 pcs.)",
          description: "Mix vegetables battered and deep fried",
          price: 16,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 12,
          name: "Onion  Bhajia (6 pcs.)",
          description: "Onion slices battered and deep fried",
          price: 15,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 4,
          count: 0,
        },
        {
          id: 13,
          name: "Chat Patta Paneer",
          description:
            "Cubes of Indian cottage cheese tossed with Indian spices",
          price: 16,
          nonVeg: "No",
          icon_id: '["1"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 14,
          name: "Paneer Tikka",
          description:
            "Chunks of cottage cheese marinated with curd and indian spices roasted in clay oven",
          price: 22,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 14,
          count: 0,
        },
        {
          id: 15,
          name: "Harabhara Kebab",
          description: "Mix vegetable cutlets with Indian spices",
          price: 14,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 6,
          count: 0,
        },
        {
          id: 16,
          name: "Ghobi 65",
          description:
            "Cauliflower battered golden fried with tomato and Indian spices",
          price: 16,
          nonVeg: "No",
          icon_id: '["1"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 7,
          count: 0,
        },
        {
          id: 17,
          name: "Aloo Tikki",
          description: "Golden fried potatoes with coriander and cumin",
          price: 12,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 8,
          count: 0,
        },
      ],
    },
    {
      id: 4,
      image: "non_veg",
      name: "Non Vegetarian Snacks",
      description: "",
      isImage: 4,
      iCnt: 11,
      items: [
        {
          id: 18,
          name: "Chicken Samosa (2 szt. / 2 pcs.)",
          description:
            "Crispy puffs stuffed with spicy chicken, potatos and green peas",
          price: 16,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 4,
          count: 0,
        },
        {
          id: 19,
          name: "Mutton Samosa (2 szt. / 2 pcs.)",
          description:
            "Crispy puffs stuffed with spicy mutton, potatos and green peas",
          price: 18,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 20,
          name: "Chicken Pakora  (6szt. / 6 pcs.)",
          description: "Pieces of grilled chicken battered and deep fried.",
          price: 16,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 5,
          count: 0,
        },
        {
          id: 21,
          name: "Chicken Lollipop (4 szt. / 4 pcs.)",
          description:
            "Chicken wings coated in spice mixed gram flour and fried.",
          price: 16,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 22,
          name: "Chicken Tikka",
          description: "Marinated chunks of chicken roasted in clay oven",
          price: 24,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 8,
          count: 0,
        },
        {
          id: 23,
          name: "Chicken Hariyali Tikka",
          description:
            "Chunks of chicken marinated with fresh herbs roasted in clay oven",
          price: 24,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 24,
          name: "Garlic Chicken Tikka",
          description:
            "Chunks of chicken marinated with garlic roasted in clay oven",
          price: 24,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 25,
          name: "Murgh Malai Kebab",
          description:
            "Supreme pieces of chicken marinated with cream and cheese roasted in clay oven",
          price: 24,
          nonVeg: "No",
          icon_id: '["4","5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 26,
          name: "Tandoori Chicken",
          description:
            "Leg and breast of chicken marinated with curd and tandoori spices roasted in clay oven",
          price: 26,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 27,
          name: "Fish Tikka",
          description:
            "Butter fish marinated with fresh herbs and roasted in clay oven",
          price: 24,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 28,
          name: "Chicken 65",
          description:
            "Chicken battered golden fried with tomato and Indian spices",
          price: 22,
          nonVeg: "No",
          icon_id: '["1"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
      ],
    },
    {
      id: 5,
      image: "veg_dish",
      name: "Vegetarian dishes",
      description: "",
      isImage: 3,
      iCnt: 15,
      items: [
        {
          id: 29,
          name: "Dal Tadka",
          description: "Yellow and red lentils cooked with Indian spices",
          price: 22,
          nonVeg: "No",
          icon_id: '["1"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 6,
          count: 0,
        },
        {
          id: 30,
          name: "Dal Makhni",
          description: "Black lentils cooked with tomato butter sauce",
          price: 22,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 31,
          name: "Vegetable  Korma",
          description:
            "Mix vegetables and chunks of cottage cheese cooked with cashewnut and cream sauce",
          price: 24,
          nonVeg: "No",
          icon_id: '["4"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 6,
          count: 0,
        },
        {
          id: 32,
          name: "Mix Kadai Vegetable",
          description:
            "Mix vegetables and chunks of cottage cheese cooked with capsicum, onion and tomato sauce",
          price: 22,
          nonVeg: "No",
          icon_id: '["2"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 8,
          count: 0,
        },
        {
          id: 33,
          name: "Chana Masala",
          description: "Chick peas cooked with Indian spices",
          price: 20,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 34,
          name: "Aloo Ghobi Curry",
          description:
            "Chunks of potato and cauliflower cooked in onion tomato sauce",
          price: 20,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 35,
          name: "Aloo Bhindi",
          description:
            "Chunks of potato and okra cooked with onion tomato sauce",
          price: 22,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 36,
          name: "Dahiwala Baingan",
          description:
            "Chunks of fresh brinjol cooked with curd and coconut sauce",
          price: 22,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 37,
          name: "Vegetable kofta",
          description: "Mix vegetables balls cooked with curry sauce",
          price: 20,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 6,
          count: 0,
        },
        {
          id: 38,
          name: "Paneer Jalfreji",
          description:
            "Chunks of cottage cheese with capsicum, onion and tomato",
          price: 24,
          nonVeg: "No",
          icon_id: '["1"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 7,
          count: 0,
        },
        {
          id: 39,
          name: "Paneer Tikka Masala",
          description:
            "Pieces of grilled Indian cottage cheese cooked with onion tomato sauce",
          price: 25,
          nonVeg: "No",
          icon_id: '["1"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 8,
          count: 0,
        },
        {
          id: 40,
          name: "Palak Paneer",
          description:
            "Spinach and chunks of cottage cheese cooked with Indian spices",
          price: 24,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 15,
          count: 0,
        },
        {
          id: 41,
          name: "Paneer Makhni",
          description:
            "Chunks of cottage cheese cooked with tomato butter sauce",
          price: 25,
          nonVeg: "No",
          icon_id: '["4"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 12,
          count: 0,
        },
        {
          id: 42,
          name: "Matar Paneer",
          description:
            "Chunks of cottage cheese and green peas cooked with tomato and cashew sauce",
          price: 22,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 5,
          count: 0,
        },
        {
          id: 43,
          name: "Paneer Kofta",
          description: "Cottage cheese balls cooked in cashew and cream sauce",
          price: 24,
          nonVeg: "No",
          icon_id: '["4"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
      ],
    },
    {
      id: 6,
      image: "non_veg_dish",
      name: "Non vegeterian dishes",
      description: "",
      isImage: 3,
      iCnt: 23,
      items: [
        {
          id: 44,
          name: "Chicken Curry",
          description: "Chunks of chicken cooked with curry sauce",
          price: 24,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 6,
          count: 0,
        },
        {
          id: 45,
          name: "Butter Chicken",
          description: "Chunks of chicken cooked with tomato butter sauce",
          price: 26,
          nonVeg: "No",
          icon_id: '["4"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 29,
          count: 0,
        },
        {
          id: 46,
          name: "Chicken Tikka Masala",
          description:
            "Chunks of grilled chicken cooked with onion tomato sauce",
          price: 26,
          nonVeg: "No",
          icon_id: '["1"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 13,
          count: 0,
        },
        {
          id: 47,
          name: "Chicken Korma",
          description: "Chunks of chicken cooked with cream-cashew",
          price: 28,
          nonVeg: "No",
          icon_id: '["4"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 20,
          count: 0,
        },
        {
          id: 48,
          name: "Chicken Lababdar",
          description:
            "Chunks of chicken cooked with cashew tomato onion sauce",
          price: 25,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 5,
          count: 0,
        },
        {
          id: 49,
          name: "Chicken Palak",
          description: "Spinach and chunks of chicken cooked with curry sauce",
          price: 25,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 5,
          count: 0,
        },
        {
          id: 50,
          name: "Chicken Jalfreji",
          description: "Chunks of chicken cooked with mix vegetable",
          price: 25,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 9,
          count: 0,
        },
        {
          id: 51,
          name: "Chicken Madras",
          description:
            "Chunks of chicken cooked with onion, capsicum and fresh hot green chilli",
          price: 28,
          nonVeg: "No",
          icon_id: '["3"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 19,
          count: 0,
        },
        {
          id: 52,
          name: "Chicken Vindaloo",
          description: "Chunks of chicken cooked with Indian spice-sour sauce",
          price: 28,
          nonVeg: "No",
          icon_id: '["3"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 8,
          count: 0,
        },
        {
          id: 53,
          name: "Methi Chicken",
          description:
            "Chunks of chicken cooked with fenugreek leaves with curry sauce",
          price: 24,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 4,
          count: 0,
        },
        {
          id: 54,
          name: "Ginger Chicken",
          description:
            "Chunks of chicken cooked with fresh ginger and Indian spices",
          price: 24,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 55,
          name: "Garlic Chicken",
          description:
            "Chunks of chicken cooked with fresh garlic and Indian spices",
          price: 25,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 6,
          count: 0,
        },
        {
          id: 56,
          name: "Chicken Do Pyaza",
          description: "Chunks of chicken cooked with onion-cashew sauce",
          price: 30,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 4,
          count: 0,
        },
        {
          id: 57,
          name: "Balti Chicken",
          description:
            "Chunks of chicken cooked with capsicum, tomato with Indian spices",
          price: 32,
          nonVeg: "No",
          icon_id: '["2"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 10,
          count: 0,
        },
        {
          id: 58,
          name: "Mutton Curry",
          description: "Chunks of mutton cooked with curry sauce",
          price: 30,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 59,
          name: "Mutton Korma",
          description: "Chunks of mutton cooked with cream- cashew sauce",
          price: 32,
          nonVeg: "No",
          icon_id: '["4"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 60,
          name: "Mutton Palak",
          description: "Spinach and chunks of mutton cooked with curry sauce",
          price: 30,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 61,
          name: "Mutton Roghan Josh",
          description:
            "Chunks of mutton cooked with Indian spices and onion sauce",
          price: 32,
          nonVeg: "No",
          icon_id: '["1"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 4,
          count: 0,
        },
        {
          id: 62,
          name: "Mutton Madras",
          description:
            "Chunks of mutton cooked with onion, capsicum and fresh hot green chili",
          price: 32,
          nonVeg: "No",
          icon_id: '["3"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 63,
          name: "Kadai Mutton",
          description: "Chunks of mutton cooked with mix veg.",
          price: 32,
          nonVeg: "No",
          icon_id: '["2"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 64,
          name: "Bhuna Gosht",
          description: "Chunks of mutton cooked with Indian spices (dry)",
          price: 30,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 65,
          name: "Balti Mutton",
          description:
            "Chunks of mutton cooked with capsicum, tomato with Indian spices",
          price: 36,
          nonVeg: "No",
          icon_id: '["2"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 66,
          name: "Ginger Mutton",
          description:
            "Chunks of mutton cooked with fresh ginger and indian spices",
          price: 35,
          nonVeg: "No",
          icon_id: '["1"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
      ],
    },
    {
      id: 7,
      image: "sea_food",
      name: "Sea food dishes",
      description: "",
      isImage: 3,
      iCnt: 7,
      items: [
        {
          id: 67,
          name: "Fish Curry",
          description: "Chunks of fish cooked with coconut based sauce",
          price: 25,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 68,
          name: "Fish Masala",
          description: "Chunks of fish cooked with onion tomato sauce",
          price: 25,
          nonVeg: "No",
          icon_id: '["1"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 69,
          name: "Fish Hydrabadi",
          description: "Chunks of fish cooked with fresh green Indian herbs",
          price: 24,
          nonVeg: "No",
          icon_id: '["2"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 70,
          name: "Garlic Fish",
          description:
            "Chunks of fish cooked with fresh garlic and Indian spices",
          price: 26,
          nonVeg: "No",
          icon_id: '["1"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 71,
          name: "Prawn Curry",
          description: "Prawns cooked with coconut and onion sauce",
          price: 35,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 4,
          count: 0,
        },
        {
          id: 72,
          name: "Prawn Jalfreji",
          description: "Prawns cooked with mix vegetable and curry sauce",
          price: 35,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 73,
          name: "Prawn Chili Garlic Masala",
          description: "Prawns cooked with garlic, chili and curry sauce",
          price: 36,
          nonVeg: "No",
          icon_id: '["3"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
      ],
    },
    {
      id: 8,
      image: "biryani",
      name: "Biryani",
      description: "",
      isImage: 4,
      iCnt: 4,
      items: [
        {
          id: 74,
          name: "Vegetable Biryani",
          description:
            "Basmati rice steamed with mix vegetables, chunks of cottage cheese and Indian spices",
          price: 24,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 75,
          name: "Chicken Biryani",
          description:
            "Basmati rice steamed with boneless chicken and fresh Indian herbs",
          price: 28,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 5,
          count: 0,
        },
        {
          id: 76,
          name: "Mutton Biryani",
          description: "Basmati rice steamed with mutton and Indian spices",
          price: 30,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 77,
          name: "Prawn Biryani",
          description:
            "Basmati rice steamed with prawns, cottage cheese and Indian spices",
          price: 35,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
      ],
    },
    {
      id: 9,
      image: "rice",
      name: "Rice",
      description: "",
      isImage: 3,
      iCnt: 7,
      items: [
        {
          id: 78,
          name: "Plain Rice",
          description: "Basmati rice",
          price: 7,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 8,
          count: 0,
        },
        {
          id: 79,
          name: "Jeera Rice",
          description: "Basmati rice fried with Indian cumin",
          price: 12,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 4,
          count: 0,
        },
        {
          id: 80,
          name: "Lemon Rice",
          description:
            "Basmati rice fried with turmeric, mustard seeds and fresh lemon juice",
          price: 12,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 81,
          name: "Safron Rice",
          description: "",
          price: 14,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 10,
          count: 0,
        },
        {
          id: 82,
          name: "Methi Pulao",
          description:
            "Basmati rice fried with fenugreek leaves and cashew nuts",
          price: 14,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 83,
          name: "Peas Pulao",
          description: "Basmati rice fried with green peas",
          price: 14,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 4,
          count: 0,
        },
        {
          id: 84,
          name: "Kashmiri Pulao",
          description: "Basmati rice fried with fresh fruits",
          price: 15,
          nonVeg: "No",
          icon_id: '["4"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
      ],
    },
    {
      id: 10,
      image: "roti",
      name: "Indian-Tandoori Breads",
      description: "",
      isImage: 3,
      iCnt: 11,
      items: [
        {
          id: 85,
          name: "Chapati",
          description: "",
          price: 5,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 4,
          count: 0,
        },
        {
          id: 86,
          name: "Tandoori Roti",
          description: "Indian bread roasted in clay oven",
          price: 6,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 4,
          count: 0,
        },
        {
          id: 88,
          name: "Plain Naan",
          description: "Plain tandoori bread made from refined flour",
          price: 7,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 24,
          count: 0,
        },
        {
          id: 89,
          name: "Butter Naan",
          description: "Indian bread with butter roasted in clay oven",
          price: 9,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 25,
          count: 0,
        },
        {
          id: 90,
          name: "Garlic Naan",
          description: "Indian bread with garlic roasted in clay oven",
          price: 10,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 41,
          count: 0,
        },
        {
          id: 91,
          name: "Keema Naan",
          description:
            "Indian bread stuffed with minced mutton and spices, roasted in clay oven",
          price: 18,
          nonVeg: "No",
          icon_id: '["1","5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 92,
          name: "Kashmiri Naan",
          description:
            "Indian bread stuffed with cheese and fresh fruit, roasted in clay oven",
          price: 15,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 93,
          name: "Aloo Parantha",
          description:
            "Indian bread stuffed with potatoes and spices, roasted in clay oven",
          price: 12,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 6,
          count: 0,
        },
        {
          id: 94,
          name: "Paneer Parantha",
          description:
            "Indian bread stuffed with cottage cheese and spices, roasted in clay oven",
          price: 16,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 95,
          name: "Mix Veg. Parantha",
          description:
            "Indian bread stuffed with mixed vegetables and spices, roasted in clay oven",
          price: 12,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 771,
          name: "Methi Roti",
          description:
            "Indian bread with fenugreek leaves roasted in clay oven",
          price: 7,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
      ],
    },
    {
      id: 11,
      image: "dosa",
      name: "Dosa",
      description: "",
      isImage: 3,
      iCnt: 5,
      items: [
        {
          id: 96,
          name: "Plain Dosa",
          description: "Pancake made from fermented rice and lentils",
          price: 16,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 97,
          name: "Masala Dosa",
          description:
            "Pancake made from fermented rice and lentils, filled with spicy mix of onions and potatoes",
          price: 22,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 8,
          count: 0,
        },
        {
          id: 98,
          name: "Chicken Masala Dosa",
          description:
            "Pancake made from fermented rice and lentils, filled with spicy mix of chicken, onion and potatoes",
          price: 28,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 99,
          name: "Pudina Dosa",
          description:
            "Pancake made from fermented rice and lentils with mint sause",
          price: 22,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 100,
          name: "Cheese Dosa",
          description:
            "Pancake made from fermented rice and lentils with cheese",
          price: 25,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
      ],
    },
    {
      id: 12,
      image: "idli",
      name: "Idli",
      description: "",
      isImage: 3,
      iCnt: 2,
      items: [
        {
          id: 101,
          name: "Plain Idli",
          description:
            "Round, fluffy south Indian streamed bread, made from ground rice or rice flour mixed \r\nwith ground urad dal, salt.",
          price: 22,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 102,
          name: "Masala Idli",
          description:
            "Round, fluffy south Indian streamed bread, made from ground rice or rice flour mixed \r\nwith ground urad dal, salt & spices",
          price: 25,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
      ],
    },
    {
      id: 13,
      image: "uttapam",
      name: "Uttapam",
      description: "",
      isImage: 3,
      iCnt: 3,
      items: [
        {
          id: 103,
          name: "Uttapam",
          description: "Indian thick pancake made from rice flour",
          price: 20,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 104,
          name: "Onion Uttapam",
          description:
            "Indian thick pancake made from rice flour  mixed with onions and Indian spices",
          price: 24,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 105,
          name: "Tomato Uttapam",
          description:
            "Indian thick pancake made from rice flour mixed with tomatoes and Indian spices",
          price: 24,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
      ],
    },
    {
      id: 14,
      image: "accompaniments",
      name: "Accompaniments",
      description: "",
      isImage: 4,
      iCnt: 2,
      items: [
        {
          id: 106,
          name: "Roasted Papad (2 szt.)",
          description: "",
          price: 4,
          nonVeg: "No",
          icon_id: '["5"]',
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 107,
          name: "Raita",
          description: "Curd mixed with onion and cucumber",
          price: 8,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
      ],
    },
    {
      id: 15,
      image: "desserts",
      name: "Dessert",
      description: "",
      isImage: 3,
      iCnt: 3,
      items: [
        {
          id: 108,
          name: "Gulab Jamun",
          description: "Deep fried milk balls, soaked in sugar cardamom syrup",
          price: 10,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 109,
          name: "Kulfi (Mango, Pista, Badam)",
          description: "Ice cream (Almonds, Pistachio & Mango)",
          price: 10,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 110,
          name: "Gajar Ka halwa",
          description: "Carrot Pudding",
          price: 10,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
      ],
    },
    {
      id: 16,
      image: "lassi",
      name: "Lassi",
      description: "",
      isImage: 3,
      iCnt: 5,
      items: [
        {
          id: 111,
          name: "Lassi Sweet",
          description: "Indian yogurt drink sweet",
          price: 9,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 3,
          count: 0,
        },
        {
          id: 112,
          name: "Lassi Salty",
          description: "Indian yogurt drink salty",
          price: 9,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 113,
          name: "Mango Lassi",
          description: "Indian mango drink with yoghurt",
          price: 10,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 18,
          count: 0,
        },
        {
          id: 114,
          name: "Banana Lassi",
          description: "Indian banana drink with yoghurt",
          price: 10,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
        {
          id: 115,
          name: "Guava Lassi",
          description: "Indian guava drink with yoghurt",
          price: 12,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 2,
          count: 0,
        },
      ],
    },
    {
      id: 17,
      image: "hot_drinks",
      name: "Hot Drinks",
      description: "",
      isImage: 3,
      iCnt: 7,
      items: [
        {
          id: 116,
          name: "Indian Tea (Chai)",
          description: "Indian tea with milk and masala",
          price: 8,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 117,
          name: "Indian Coffee",
          description: "Indian coffee with milk and masala",
          price: 8,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 118,
          name: "Ayurvedic Tea",
          description: "",
          price: 7,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 119,
          name: "Black Tea",
          description: "",
          price: 7,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 120,
          name: "Espresso Small",
          description: "",
          price: 7,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 789,
          name: "Espresso Big",
          description: "",
          price: 8,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 790,
          name: "Indian Coffee",
          description: "",
          price: 8,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
      ],
    },
    {
      id: 18,
      image: "indian_cold_drinks",
      name: "Indian Cold Drinks",
      description: "",
      isImage: 4,
      iCnt: 6,
      items: [
        {
          id: 121,
          name: "Ginger Lemon Drink (200ml)",
          description: "",
          price: 10,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 1,
          count: 0,
        },
        {
          id: 122,
          name: "Mango Juice (200ml)",
          description: "",
          price: 6,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 123,
          name: "Lychee Juice (200ml)",
          description: "",
          price: 6,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 124,
          name: "Guava Juice (200ml)",
          description: "",
          price: 6,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 125,
          name: "Lemonade Sweet  (200ml)",
          description: "",
          price: 10,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 126,
          name: "Lemonade Salty (200ml)",
          description: "",
          price: 10,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
      ],
    },
    {
      id: 19,
      image: "cold_drinks",
      name: "Cold Drinks",
      description: "",
      isImage: 3,
      iCnt: 9,
      items: [
        {
          id: 127,
          name: "Coca Cola / Zero (200ml)",
          description: "",
          price: 5,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 128,
          name: "Coca Cola (500ml)",
          description: "",
          price: 6,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 129,
          name: "Fanta  (200ml)",
          description: "",
          price: 5,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 130,
          name: "Sprite  (200ml)",
          description: "",
          price: 5,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 131,
          name: "Nestea lemon / peach  (200ml)",
          description: "",
          price: 5,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 132,
          name: "Tonic  (200ml)",
          description: "",
          price: 6,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 133,
          name: "Woda niegazowana / gazowana  (200ml)",
          description: "",
          price: 5,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 134,
          name: "Woda niegazowana / gazowana  (500ml)",
          description: "",
          price: 6,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
        {
          id: 135,
          name: "Juice Cappy Tomato / Orange / Apple",
          description: "",
          price: 5,
          nonVeg: "No",
          icon_id: "",
          isSpecial: "No",
          topping_id: "",
          isImage: 0,
          type: "i",
          liked: 0,
          likes: 0,
          count: 0,
        },
      ],
    },
  ],
};

export default (state = initialState, action) => {
  switch (action.type) {
    case `${GET_MENU}_PENDING`:
      return {
        ...state,
        loading: true,
      };
    case `${GET_MENU}_FULFILLED`: {
      //get menu item from store
      return {
        ...state,
        loading: false,
      };
    }
    case `${GET_MENU}_REJECTED`: {
      return {
        ...state,
        loading: false,
      };
    }
    case `ADD_TO_CART`: {
      //find subitem from item and update count
      let cro = state.menu;
      cro &&
        cro.map((item) => {
          if (item.id === action.payload.itemId) {
            item.items.map((subItem) => {
              if (subItem.id === action.payload.id) {
                subItem.count = 1;
              }
            });
          }
        });
      return {
        ...state,
        loading: false,
        menu: Object.assign(state.menu, ...cro),
      };
    }
    case `REMOVE_FROM_CART`: {
      //find subitem from item and update count
      let cro = state.menu;
      cro &&
        cro.map((item) => {
          if (item.id === action.payload.itemId) {
            item.items.map((subItem) => {
              if (subItem.id === action.payload.id) {
                subItem.count = 0;
              }
            });
          }
        });
      return {
        ...state,
        loading: false,
        menu: Object.assign(state.menu, ...cro),
      };
    }
    case `INCREASE_QUANTITY`: {
      //find subitem from item and increment count
      let cro = state.menu;
      cro &&
        cro.map((item) => {
          item.items.map((subItem) => {
            if (subItem.id === action.payload.id) {
              subItem.count++;
            }
          });
        });
      return {
        ...state,
        loading: false,
        menu: Object.assign(state.menu, ...cro),
      };
    }
    case `DECREASE_QUANTITY`: {
      //find subitem from item and decrement count
      let cro = state.menu;
      cro &&
        cro.map((item) => {
          item.items.map((subItem) => {
            if (subItem.id === action.payload.id) {
              subItem.count--;
            }
          });
        });
      return {
        ...state,
        loading: false,
        menu: Object.assign(state.menu, ...cro),
      };
    }
    case `LIKE_ITEM`: {
      //find subitem from item and update likes
      let cro = state.menu;
      cro &&
        cro.map((item) => {
          item.items.map((subItem) => {
            if (subItem.id === action.payload.id) {
              subItem.liked = 1;
              subItem.likes += 1;
            }
          });
        });
      return {
        ...state,
        loading: false,
        menu: Object.assign(state.menu, ...cro),
      };
    }
    case `UNLIKE_ITEM`: {
      //find subitem from item and update likes
      let cro = state.menu;
      cro &&
        cro.map((item) => {
          item.items.map((subItem) => {
            if (subItem.id === action.payload.id) {
              subItem.liked = 0;
              subItem.likes -= 1;
            }
          });
        });
      return {
        ...state,
        loading: false,
        menu: Object.assign(state.menu, ...cro),
      };
    }
    default:
      return state;
  }
};
